matrix:
  include:
    
    - language: python
      jobs:        
        include:
          # perform a linux build
          - services: docker
            env: CIBW_BEFORE_BUILD="yum install -y lapack-devel blas-devel"
          # and a mac build
          - os: osx
            language: shell
          # and a windows build
          - os: windows
            language: shell
            before_install:
              - choco install python --version 3.8.0
              - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      env:        
        global:
          - CIBW_BEFORE_BUILD="yum install -y lapack-devel blas-devel"
          - TWINE_USERNAME=__token__
          # Note: TWINE_PASSWORD is set to a PyPI API token in Travis settings
      install:
        - python3 -m pip install cibuildwheel==1.3.0
      script:
        # build the wheels, put them into './wheelhouse'
        - cd python-package; CIBW_BEFORE_BUILD="yum install -y lapack-devel blas-devel" python3 -m cibuildwheel --output-dir wheelhouse
      after_success:
        # if the release was tagged, upload them to PyPI
        - |
          if [[ $TRAVIS_TAG ]]; then
          python3 -m pip install twine
          python3 -m twine upload wheelhouse/*.whl
          fi

    - language: r    
      r: release
      warnings_are_errors: true
      cache: packages    
      addons:
        apt:
          packages:
            - r-cran-covr
            - r-cran-devtools
            - r-cran-futile.logger
            - r-cran-lava
            - r-cran-optimx          
            - r-cran-rcpp
            - r-cran-rcpparmadillo
            - r-cran-testthat
      install:
        - echo    
      script:
        - make checkr pkg=targeted

    - language: cpp
      os:
        - linux
      compiler: clang
      addons:
        apt:
          packages:
            - cmake
            - liblapack-dev
            - libblas-dev
      script:
        - make init
        - make test
