name: targeted python wheels

on:
  push:
    # branches-ignore:
      # - develop
    branches:
      - deploy

jobs:
  linux_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout repository incl. submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel --upgrade
      - name: Build wheels
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_I686_IMAGE: manylinux2014
          CIBW_SKIP: cp27-* cp35-* *musl* pp*
          CIBW_BEFORE_BUILD: yum install -y make lapack-devel blas-devel python-devel; pip install cmake; cd lib/armadillo; cmake -B build && cd build; make install; cd ../../..
        run: |
          make py_export pkg=targeted
          cd build/python/targeted; python3 -m cibuildwheel --output-dir wheelhouse
      - name: Build source package
        run: |
          cd build/python/targeted
          python3 setup.py sdist
      - name: Upload to PyPi
        # https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
        #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python3 -m pip install -U setuptools twine
          cd build/python/targeted
          python3 -m twine upload --skip-existing dist/*.tar.gz
          python3 -m twine upload --skip-existing wheelhouse/*.whl

  macosx_build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout repository incl. submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel --upgrade
      - name: Build wheels
        env:
          CIBW_BEFORE_BUILD: pip install cmake
          CIBW_SKIP: cp27-* cp35-* pp*
          CIBW_ARCHS: x86_64 arm64
        run: |
          make py_export pkg=targeted
          cd build/python/targeted; python3 -m cibuildwheel --output-dir wheelhouse
      - name: Upload to PyPi
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python3 -m pip install -U setuptools twine
          cd build/python/targeted
          python3 -m twine upload --skip-existing wheelhouse/*.whl
